### ISSUE TITLE
License issues

### ISSUE THREAD

**Issue by mikolalysenko** [shachaf/jsgif#3]
Hi, I would like to make a CommonJS port of this library which is suitable for use with npm/node.js, but I couldn't find any license info.

Can you add a license file so that it is possible to use this code in open source projects?  (MIT or BSD would be preferable).

**Comment by shachaf** [comment]
There's already a [LICENSE file](https://github.com/shachaf/jsgif/blob/master/LICENSE) with the MIT license.

I can't say I recommend using this for anything serious, though...
