### ISSUE TITLE
So how do you download/use this thing?

### ISSUE THREAD

**Issue by DoomT-AliW** [shachaf/jsgif#5]
So I found the website, http://slbkbs.org/jsgif/

It just shows an example gif from wiki, but it doesn't explain how to actually use it in the browser. Like, should I download the source from the repo and execute some files or, download an extension from my browser (which I couldn't find), or...?

**Comment by shachaf** [comment]
Just click the `jsgif` link and then click the sample GIF image to try it. To use it on other pages, bookmark the link.
